### PR TITLE
Suggest edit link

### PR DESCRIPTION
**Pull request by ryanburnette**
Working on #2

- [x] LInk in postmeta-footer
- [x] Responsive alignment
- [x] Compose href
- [x] On only when `.Site.Params.suggestedits` is set to `true`
- [x] Document in readme
- [x] meta fields

### CODE REVIEW

**Comment by ryanburnette** [comment]
@coolaj86 How do we create the href for the suggest edit link?

**Comment by coolaj86** [comment]
We need:
- `.Site.Params.gitHost` (custom) `gitea`
- `.Site.Params.gitBranch` (custom) `main`
- `.Site.Params.gitBaseURL` (custom) `https://git.coolaj86.com/coolaj86/blog`
- `.File.Dir` and `.File.LogicalName` (Hugo)

I don't know the exact syntax off the top of my head, but something like this:
```html
{{ if eq .Site.Params.gitHost "gitea" }}
  {{ .Site.Params.gitBaseURL }}/_edit/{{ .Site.Params.gitBranch }}/{{ .File.Dir }}/{{ .File.LogicalName }}
{{ else }}
  {{ .Site.Params.gitBaseURL }}/edit/{{ .Site.Params.gitBranch }}/{{ .File.Dir }}/{{ .File.LogicalName }}
{{ end }}
```

Between GitHub, Gitea, and GitLab, there's a slight differences between the URL style - `edit` vs `_edit`. I believe GitLab is the same as GitHub in this regard.

Github:
- https://github.com/org/proj/edit/main/content/blog/hello.md
- https://github.com/BeyondCodeBootcamp/beyondcodebootcamp.com/edit/main/articles/how-to-create-a-server.md
Gitea:
- https://git.rootprojects.org/org/proj/_edit/main/content/blog/hello.md
- https://git.rootprojects.org/root/therootcompany.com/_edit/main/content/blog/best-pattern-for-async-routes-in-expressjs.md

**Comment by ryanburnette** [comment]
@coolaj86 This is ready to go. I'll probably merge this in favor of #17, but we can discuss first.

**Comment by ryanburnette** [comment]
@coolaj86 I did use some of the template work you did from your pr. I tried to merge it so you got credit for the commit, but I couldn't get it to work. I know you probably don't care.

**Pull request merged**
